### PR TITLE
Bugfix in Horner's scheme

### LINKED ISSUE #78: Bug in Horner's scheme
### Description

Horner's scheme as it is implemented now gives wrong results.

### Observed Behaviour

```julia
julia> using Polynomials
julia> p1 = Poly([Inf, Inf])
Poly(Inf + Inf⋅x)
julia> p1(Inf)
NaN
julia> p1(-Inf)
NaN
julia> p1(0)
NaN
julia> p2 = Poly([0, Inf])
Poly(Inf⋅x)
julia> p2(-Inf)
NaN
```

### Desired Behaviour

```julia
julia> using Polynomials
julia> p1 = Poly([Inf, Inf])
Poly(Inf + Inf⋅x)
julia> p1(Inf)
Inf
julia> p1(-Inf)
NaN
julia> p1(0)
NaN
julia> p2 = Poly([0, Inf])
Poly(Inf⋅x)
julia> p2(-Inf)
-Inf
```

### PR DESCRIPTION
**Pull request by aytekinar**
Closes #78.

### CODE REVIEW

File: src/Polynomials.jl [hunk 1]
```diff
@@ -372,7 +372,7 @@ function polyval{T,S}(p::Poly{T}, x::S)
     if lenp == 0
         return zero(R) * x
     else
-        y = convert(R, p[end]) + zero(T)*x
+        y = convert(R, p[end])
```
Comment (jverzani) [inline src/Polynomials.jl]: I don't understand why `zero(T)*x` is here. If there is any reason, perhaps changing to `zero(T)*zero(x)`?

Comment (aytekinar) [inline src/Polynomials.jl]: actually, I do not see any benefit in using `zero(T)*zero(x)`. since we have `convert(R, p[end])` where `R = promote_type(T,S)`, `zero(x)` will be automatically promoted to `R`. For normal numbers, I mean standard `Number`s, `zero(x)` is not needed at all. Then, if there is a custom type `Type <: Number`, it might make sense to use `zero(x)` and rely on the conversion rules among `Number`s.

What do you think?

Do you think we can push these issues (i.e., Horner's bug, `Base./` and perhaps `polyder`) this weekend?

Comment (aytekinar) [inline src/Polynomials.jl]: thanks! that'd be great! :)

**Comment by jverzani** [comment]
Thanks!
