### PR TITLE
Minor changes preparing for v0.6

### LINKED ISSUE #100: v0.6 related changes
### Description

Some changes might be needed to prepare the package for `v0.6`:

- [x] `VERSION < v"0.6.0-dev"` fails in https://juliabox.com with the `v0.6-dev` kernel,
- [x] `Array(T, n)` results in deprecation warnings. Better to change it to `Vector{T}(n)`,
- [x] `convert{T,S}(p::Poly{T}, s::S)` should always convert `s` to `Poly{T}`, but not to `Poly{promote_type(T,S)}`. How could we, otherwise, have `convert(Poly{Float64}, BigFloat(5))` do what we exactly want?
- [x] That would be great if we relaxed the requirements in `.travis.yml` file. Allowing for failures in `nightly` builds will help develop the package for supported environments in a smoother way. Problem here is that #98 and #99 are failing in `nightly` in a different place from those introduced in the corresponding PRs.

### PR DESCRIPTION
**Pull request by aytekinar**
Minor changes introduced in order to prepare the package for v0.6:

- [x] `VERSION < v"0.6"` added, since the previous implementation
  was failing in juliabox.com with the `v0.6-dev` kernel,
- [x] Relaxed the build matrix in `.travis.yml` file,
- [x] Changed from `Array(T, n)` to `Vector{T}(n)` to get rid of the
  deprecation warnings, and,
- [x] Fixed `convert` rules in two ways: (1) added `map` version to the
  `AbstractArray` case to cover for everything, (2) removed the
  `promote_type` section from conversions.

As for the last item above, `convert{T,S}(::Type{Poly{T}}, n::S)` should
ALWAYS convert to `Poly{T}`, not to `Poly{promote_type(T,S)}`.

Closes #100.

### CODE REVIEW

File: src/Polynomials.jl [hunk 1]
```diff
@@ -109,9 +109,8 @@ include("show.jl") # display polynomials.
 
 convert{T}(::Type{Poly{T}}, p::Poly{T}) = p
 convert{T}(::Type{Poly{T}}, p::Poly) = Poly(convert(Vector{T}, p.a), p.var)
-convert{T, S<:Number}(::Type{Poly{T}}, x::S, var::SymbolLike=:x) = Poly(promote_type(T, S)[x], var)
-convert{T, S<:Number}(::Type{Poly{T}}, x::Vector{S}, var::SymbolLike=:x) = (R = promote_type(T,S); Poly(convert(Vector{R},x), var))
-convert{T, S<:Number,n}(::Type{Poly{T}}, x::Array{S,n}, var::SymbolLike=:x) = map(el->convert(Poly{promote_type(T,S)},el,var),x)
+convert{T, S<:Number}(::Type{Poly{T}}, x::S, var::SymbolLike=:x) = Poly(T[x], var)
```
Comment (jverzani) [inline src/Polynomials.jl]: This makes more sense to me. I wonder if any code relies on this. We'll find out.

**Comment by jverzani** [comment]
This looks good. Thanks
